[build]
publish = "public"
command = "git submodule update --init --recursive --depth 1 && npm run build"
functions = "./functions"

[build.environment]
NODE_VERSION = "18"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "git submodule update --init --recursive --depth 1 && npm run build"

[context.split1.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "git submodule update --init --recursive --depth 1 && npm run build:preview"

[context.branch-deploy]
command = "git submodule update --init --recursive --depth 1 && npm run build:preview"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/setup/productionize/*"
  to = "/docs/setup/productionize/:splat"
  status = 301
  force = false

[[redirects]]
 from = "/setup/install/*"
 to = "/docs/setup/install/:splat"
 status = 301
 force = false

[[redirects]]
  from = "/setup/artifacts/*"
  to = "/docs/setup/other_config/artifacts/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/setup/bakery/*"
  to = "/docs/setup/other_config/bakery/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/setup/security/*"
  to = "/docs/setup/other_config/security/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/setup/triggers/*"
  to = "/docs/setup/other_config/triggers/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/setup/triggers/*"
  to = "/docs/setup/other_config/triggers/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/setup/spin/*"
  to = "/docs/setup/other_config/spin/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/setup/ci/*"
  to = "/docs/setup/other_config/ci/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/setup/monitoring/*"
  to = "/docs/setup/other_config/monitoring/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/setup/ci/*"
  to = "/docs/setup/other_config/ci/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/setup/canary/*"
  to = "/docs/setup/other_config/canary/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/setup/features/*"
  to = "/docs/setup/other_config/features/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/setup/configuration/*"
  to = "/docs/setup/other_config/configuration/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/setup/quickstart/*"
  to = "/docs/setup/install/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/guides/*"
  to = "/docs/guides/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/reference/*"
  to = "/docs/reference/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/community/releases/*"
  to = "/docs/releases/:splat"
  status = 301
  force = false
  
[[redirects]]
  from = "/community/*"
  to = "/docs/community/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/docs/reference/artifacts/*"
  to = "/docs/reference/artifacts-legacy/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/docs/reference/artifacts-with-artifactsrewrite/*"
  to = "/docs/reference/ref-artifacts/:splat"
  status = 301
  force = false

[[redirects]]
from = "/docs/reference/refs-artifactsrewrite/*"
to = "/docs/reference/artifacts/:splat"
status = 301
force = false


# headers  https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file
# https://cloud-armory.slack.com/archives/CH4RVCCTS/p1608572781420500
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
